---
- name: Check Homebrew binary locations
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - /opt/homebrew/bin/brew
    - /usr/local/bin/brew
  register: brew_checks

- name: Fail if Homebrew is not installed
  ansible.builtin.fail:
    msg: "Homebrew must be installed."
  when: brew_checks.results | selectattr('stat.exists') | list | length == 0

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew_casks }}"
    state: present

- name: Configure Kopia
  ansible.builtin.include_tasks: kopia.yml
